#services:
#  box:
#    image: python:3.10
#    working_dir: /home/dev
#    command: /bin/bash
#    volumes:
#      - $PWD:/home/dev
#    stdin_open: true
#    tty: true
#
services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
